### ISSUE TITLE
crashing when notification closes while mouse is hovering?

### ISSUE THREAD

**Issue by lavitt** [Toqozz/wired-notify#5] opened 2021-07-13 19:01 UTC
here's the output with `RUST_BACKTRACE=full`

Couldn't load a config because we couldn't find one, so will use default.
Acquired notification bus name.
DBus Init Success.
[src/bus/dbus.rs:251] hints.get("urgency") = Some(
    U8(
      1,
    ),
)
thread 'main' panicked at 'called \`Option::unwrap()\` on a \`None\` value', src/management/mod.rs:208:49
stack backtrace:
   0:     0x56224128d090 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h065a832482834301
   1:     0x5622412b362f - core::fmt::write::h2b69bbb8432077e1
   2:     0x562241289e55 - std::io::Write::write_fmt::h7ba36cb591b30c0e
   3:     0x56224128f12b - std::panicking::default_hook::{{closure}}::h4a86d06b0c355a30
   4:     0x56224128ebfd - std::panicking::default_hook::hf15750add1a66ef3
   5:     0x56224128f74d - std::panicking::rust_panic_with_hook::h890451a2e631ad12
   6:     0x56224128f2a7 - std::panicking::begin_panic_handler::{{closure}}::h33319620d050e505
   7:     0x56224128d52c - std::sys_common::backtrace::__rust_end_short_backtrace::h41c9a51013c798bc
   8:     0x56224128f239 - rust_begin_unwind
   9:     0x5622410a4251 - core::panicking::panic_fmt::h4cabb5e7744685f2
  10:     0x5622410a419d - core::panicking::panic::h922388c45c3756a7
  11:     0x5622410c826c - wired::management::NotifyWindowManager::process_event::hb206944b544f469b
  12:     0x5622410fd831 - wired::main::{{closure}}::he400883b0fbe329d
  13:     0x5622410f940b - winit::platform_impl::platform::sticky_exit_callback::h4b0235a2b03a5d74
  14:     0x5622411067d8 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::h431e38761293b294
  15:     0x5622410dd4fd - winit::platform_impl::platform::x11::EventLoop<T>::run_return::hbbe4c1990aca263d
  16:     0x56224111a92b - wired::main::h5c9df09baa00d3dd
  17:     0x5622410c1fa3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h243499eb11bd21ac
  18:     0x56224111cdf9 - std::rt::lang_start::{{closure}}::h7c54d5a0d18cc90c
  19:     0x56224128fc4a - std::rt::lang_start_internal::had36925571e04f2b
  20:     0x56224111b452 - main
  21:     0x7f35bc0c8e0a - __libc_start_main
                               at /builddir/glibc-2.32/csu/../csu/libc-start.c:314:16
  22:     0x5622410a49ca - _start
                               at /builddir/glibc-2.32/csu/../sysdeps/x86_64/start.S:120
  23:                0x0 - <unknown>

**Comment by Toqozz** [comment] 2021-07-14 01:07
Thanks for the issue!

Most likely this is some race condition where the window is destroyed but it still has events to process, but I am unable to reproduce.

Regardless, this should be fixed now by just handling the `Option` properly instead of lazily unwrapping.

**Closed by Toqozz** 2021-07-14 01:07 UTC
