### ISSUE TITLE
Icon paths

### ISSUE THREAD

**Issue by AnkushRoy-code** [Toqozz/wired-notify#155] opened 2024-10-18 13:51 UTC
Is it possible to pre-define icon paths? Something like what dunst has. Every time I send notifications I have to use absolute paths to the icons. I think some applications I use which send notification do not support this. They just use normal icon names.

**Comment by Toqozz** [comment] 2024-11-03 06:31
Duplicate of #150.

**Closed by Toqozz** 2024-11-03 06:31 UTC
