### ISSUE TITLE
Notification doesn't resize when replaced

### ISSUE THREAD

**Issue by wezzynl** [Toqozz/wired-notify#135] opened 2024-02-20 09:47 UTC
I upgraded to 0.10.5, coming from 0.10.2 (rev: 9bd2ca3625091ed2b0e35321ee41a5d5e1327a4b) and it looks like notifcations do not resize correctly anymore when using the `--replace=<notification-id>`-argument.

On version 0.10.2, replacing the notification would resize it so that the contents fit (longer text would push the notification wider). In 0.10.5 it seems to stick to the initial notification's width/height and goes wonky with the border and cuts off text that is wider.

Here's a screenshot of what I mean. It are two consecutive notifications that are being replaced after a keypress:

![image](https://github.com/Toqozz/wired-notify/assets/5656741/6df00579-76a5-4b98-a72e-c474a89b822a)

![image](https://github.com/Toqozz/wired-notify/assets/5656741/88c15a61-d347-486b-98ca-8385a206f579)

Notice how the height gets cut off and how the slightly wider width wonks up the border.

P.S. Thank you for your work on wired, it's awesome.

**Comment by Toqozz** [comment] 2024-02-22 08:34
Thanks for the report!

It's highly likely that 5633397 is the cause of this.  We probably just need to make sure that we do the calculation again when replacing windows.

**Comment by Toqozz** [comment] 2024-02-29 07:21
Should be fixed in latest master.

**Closed by Toqozz** 2024-02-29 07:21 UTC
